# Generated by Django 4.1.7 on 2023-03-13 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_document_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.userinfo'),
        ),
    ]
